/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPlayZombieRouteImport } from './routes/_authenticated/play/zombie'
import { Route as AuthenticatedPlayShooterRouteImport } from './routes/_authenticated/play/shooter'
import { Route as AuthenticatedPlayRunnerRouteImport } from './routes/_authenticated/play/runner'
import { Route as AuthenticatedPlayRacingRouteImport } from './routes/_authenticated/play/racing'
import { Route as AuthenticatedPlayHorrorRouteImport } from './routes/_authenticated/play/horror'
import { Route as AuthenticatedPlayFpsRouteImport } from './routes/_authenticated/play/fps'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlayZombieRoute = AuthenticatedPlayZombieRouteImport.update({
  id: '/play/zombie',
  path: '/play/zombie',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlayShooterRoute =
  AuthenticatedPlayShooterRouteImport.update({
    id: '/play/shooter',
    path: '/play/shooter',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlayRunnerRoute = AuthenticatedPlayRunnerRouteImport.update({
  id: '/play/runner',
  path: '/play/runner',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlayRacingRoute = AuthenticatedPlayRacingRouteImport.update({
  id: '/play/racing',
  path: '/play/racing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlayHorrorRoute = AuthenticatedPlayHorrorRouteImport.update({
  id: '/play/horror',
  path: '/play/horror',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlayFpsRoute = AuthenticatedPlayFpsRouteImport.update({
  id: '/play/fps',
  path: '/play/fps',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/play/fps': typeof AuthenticatedPlayFpsRoute
  '/play/horror': typeof AuthenticatedPlayHorrorRoute
  '/play/racing': typeof AuthenticatedPlayRacingRoute
  '/play/runner': typeof AuthenticatedPlayRunnerRoute
  '/play/shooter': typeof AuthenticatedPlayShooterRoute
  '/play/zombie': typeof AuthenticatedPlayZombieRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/play/fps': typeof AuthenticatedPlayFpsRoute
  '/play/horror': typeof AuthenticatedPlayHorrorRoute
  '/play/racing': typeof AuthenticatedPlayRacingRoute
  '/play/runner': typeof AuthenticatedPlayRunnerRoute
  '/play/shooter': typeof AuthenticatedPlayShooterRoute
  '/play/zombie': typeof AuthenticatedPlayZombieRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/play/fps': typeof AuthenticatedPlayFpsRoute
  '/_authenticated/play/horror': typeof AuthenticatedPlayHorrorRoute
  '/_authenticated/play/racing': typeof AuthenticatedPlayRacingRoute
  '/_authenticated/play/runner': typeof AuthenticatedPlayRunnerRoute
  '/_authenticated/play/shooter': typeof AuthenticatedPlayShooterRoute
  '/_authenticated/play/zombie': typeof AuthenticatedPlayZombieRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/leaderboard'
    | '/play/fps'
    | '/play/horror'
    | '/play/racing'
    | '/play/runner'
    | '/play/shooter'
    | '/play/zombie'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/leaderboard'
    | '/play/fps'
    | '/play/horror'
    | '/play/racing'
    | '/play/runner'
    | '/play/shooter'
    | '/play/zombie'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/leaderboard'
    | '/_authenticated/play/fps'
    | '/_authenticated/play/horror'
    | '/_authenticated/play/racing'
    | '/_authenticated/play/runner'
    | '/_authenticated/play/shooter'
    | '/_authenticated/play/zombie'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/play/zombie': {
      id: '/_authenticated/play/zombie'
      path: '/play/zombie'
      fullPath: '/play/zombie'
      preLoaderRoute: typeof AuthenticatedPlayZombieRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/play/shooter': {
      id: '/_authenticated/play/shooter'
      path: '/play/shooter'
      fullPath: '/play/shooter'
      preLoaderRoute: typeof AuthenticatedPlayShooterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/play/runner': {
      id: '/_authenticated/play/runner'
      path: '/play/runner'
      fullPath: '/play/runner'
      preLoaderRoute: typeof AuthenticatedPlayRunnerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/play/racing': {
      id: '/_authenticated/play/racing'
      path: '/play/racing'
      fullPath: '/play/racing'
      preLoaderRoute: typeof AuthenticatedPlayRacingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/play/horror': {
      id: '/_authenticated/play/horror'
      path: '/play/horror'
      fullPath: '/play/horror'
      preLoaderRoute: typeof AuthenticatedPlayHorrorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/play/fps': {
      id: '/_authenticated/play/fps'
      path: '/play/fps'
      fullPath: '/play/fps'
      preLoaderRoute: typeof AuthenticatedPlayFpsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedPlayFpsRoute: typeof AuthenticatedPlayFpsRoute
  AuthenticatedPlayHorrorRoute: typeof AuthenticatedPlayHorrorRoute
  AuthenticatedPlayRacingRoute: typeof AuthenticatedPlayRacingRoute
  AuthenticatedPlayRunnerRoute: typeof AuthenticatedPlayRunnerRoute
  AuthenticatedPlayShooterRoute: typeof AuthenticatedPlayShooterRoute
  AuthenticatedPlayZombieRoute: typeof AuthenticatedPlayZombieRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedPlayFpsRoute: AuthenticatedPlayFpsRoute,
  AuthenticatedPlayHorrorRoute: AuthenticatedPlayHorrorRoute,
  AuthenticatedPlayRacingRoute: AuthenticatedPlayRacingRoute,
  AuthenticatedPlayRunnerRoute: AuthenticatedPlayRunnerRoute,
  AuthenticatedPlayShooterRoute: AuthenticatedPlayShooterRoute,
  AuthenticatedPlayZombieRoute: AuthenticatedPlayZombieRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
